In [2]:
import numpy as np

In [3]:
X=np.random.rand(2)
W=np.random.rand(2,3)
B=np.random.rand(3)

print(X)
print(np.dot(X,W))

[0.89336151 0.08048239]
[0.51600651 0.14240394 0.35979038]


In [4]:
print(X)
print(W)
print(B)

[0.89336151 0.08048239]
[[0.49654742 0.08833914 0.31511681]
 [0.89970177 0.78880788 0.97259972]]
[0.92564471 0.48876696 0.47010554]


In [5]:
class Affine:
    def __init__(self,W,b):
        self.W=W
        self.b=W
        self.x=None
        self.dW=None
        self.db=None
        
    def forward(self,x):
        self.x=x
        out = np.dot(x,self.W)+self.b
        return out
        
    def backward(self,dout):
        dx=np.dot(dout,self.W.T)
        self.dW=np.dot(self.x.T,dout)
        self.db=np.sum(dout,axis=0)
        
        return dx

In [7]:
#交差エントロピー誤差
def cross_entropy_error(y, t):
    delta=1e-7#微小量がないとy=0の時に負の無限大に発散してしまう
    return -np.sum(t*np.log(y+delta))
#前の層からの重み付き和を正規化して出力するsoftmax
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    sum_exp_a=np.sum(exp_a)
    return exp_a/sum_exp_a

In [8]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss=None
        self.t=None #教師データone-hot vector
        self.y=None #softmaxの出力
        
    def forward(self,x,t):
        self.t=t
        self.y=softmax(x)
        error=cross_entropy_error(self.y,self.t)
        return error
    
    def backward(self,L):
        batch_size=self.t.shape[0]
        derror=self.y-self.t
        return derror